apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: triage-agent
  namespace: kagent
spec:
  description: Ingests JSON alerts from AWS sources, labels them with source, event type, priority, and environment, then forwards enriched messages to a downstream RCA agent.
  type: BYO
  byo:
    deployment:
      image: ghcr.io/imknysh/triage-agent:latest
      env:
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-providers-api-keys
              key: OPENAI_API_KEY
---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: rca-agent
  namespace: kagent
spec:
  description: AI-powered Root Cause Analysis agent
  type: BYO
  byo:
    deployment:
      image: ghcr.io/imknysh/rca-agent:latest
      env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-providers-api-keys
              key: OPENAI_API_KEY
---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: k8s-a2a-agent
  namespace: kagent
spec:
  description: An example A2A agent that knows how to use Kubernetes tools.
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: |-
        You are an expert Kubernetes agent that uses tools to help users.
    tools:
      - type: McpServer
        mcpServer:
          name: kagent-tool-server
          kind: RemoteMCPServer
          toolNames:
          - k8s_get_resources
          - k8s_get_available_api_resources
    a2aConfig:
      skills:
      - id: get-resources-skill
        name: Get Resources
        description: Get resources in the Kubernetes cluster
        inputModes:
        - text
        outputModes:
        - text
        tags:
        - k8s
        - resources
        examples:
        - "Get all resources in the Kubernetes cluster"
        - "Get the pods in the default namespace"
        - "Get the services in the istio-system namespace"
        - "Get the deployments in the istio-system namespace"
        - "Get the jobs in the istio-system namespace"
        - "Get the cronjobs in the istio-system namespace"
        - "Get the statefulsets in the istio-system namespace"
