apiVersion: v1
kind: Namespace
metadata:
  name: ai-inventory-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ai-inventory
  namespace: ai-inventory-system
spec:
  interval: 1h
  url: oci://ghcr.io/agentregistry-dev/agentregistry/charts/agentregistry
  ref:
    tag: "v0.3.2"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ai-inventory
  namespace: ai-inventory-system
spec:
  interval: 1h
  releaseName: ai-inventory
  chartRef:
    kind: OCIRepository
    name: ai-inventory
    namespace: ai-inventory-system
  install:
    createNamespace: true
  values:
    config:
      existingSecret: ai-inventory-secret