apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-replicator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mittwald
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.mittwald.de
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: kubernetes-replicator
spec:
  interval: 1h
  releaseName: kubernetes-replicator
  chart:
    spec:
      chart: kubernetes-replicator
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  install:
    createNamespace: true
