apiVersion: v1
kind: Namespace
metadata:
  name: qdrant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 1h
  url: https://qdrant.github.io/qdrant-helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 10m
  chart: qdrant
  sourceRef:
    kind: HelmRepository
    name: qdrant
  version: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 1h
  releaseName: qdrant
  chartRef:
    kind: HelmChart
    name: qdrant
    namespace: qdrant
  install:
    createNamespace: true